issuetracker_proj/issuetracker/urls.py
from django.conf.urls import patterns, url
from issuetracker.views import IssueListView, IssueDetailView, IssueCreateView, \
    IssueUpdateView, IssueCommentCreateView, IssueNotificationsView, IssueModerationView

urlpatterns = patterns('',
    #url(r'^$', views.index, name='issue_home'),
    url(r'^$', IssueListView.as_view(), name='issue_home'),
    url(r'^(?P<pk>\d+)/', IssueDetailView.as_view(), name='issue_detail'),
    url(r'^edit/(?P<pk>\d+)', IssueUpdateView.as_view(), name='issue_update'),
    url(r'^new/', IssueCreateView.as_view(), name='issue_create'),
    url(r'^comment/new/(?P<pk>\d+)', IssueCommentCreateView.as_view(), name='issue_comment_create'),
    url(r'^notifications/', IssueNotificationsView.as_view(),name='issue_notifications_list'),
    url(r'^moderate/(?P<issue_id>\d+)', IssueModerationView.as_view(),name='issue_moderation')
    #url(r'^itmod/(?P<pk>\d+)/', views.itmod_set, name='itmod_set')
    
)

issuetracker_proj/issuetracker_proj/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from tastypie.api import Api
from issuetracker.api import IssueResource

v1_api = Api(api_name='v1')
v1_api.register(IssueResource())


urlpatterns = patterns('',
    # Examples:
    url(r'^issue/', include('issuetracker.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(v1_api.urls)),
)

urlpatterns += patterns(
    'django.contrib.auth.views',
    url(r'^login/','login',
    {'template_name': 'login.html'},
    name='issue_login'),
    
    url(r'^logout/','logout',
    {'next_page': 'issue_home'},
    name='issue_logout'),
)

issuetracker_proj/issuetracker/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

class CategoryManager(models.Manager):
    def frontend_count(self):
        return super(CategoryManager, self).get_query_set().filter(category='F').count()

class Issue(models.Model):
    CATEGORIES = (
        ('F', 'Frontend'),
        ('B', 'Backend'),
        ('U', 'UX/Design'),
        ('C', 'CRM'),
    )
    title = models.CharField(max_length=140)
    description = models.TextField()
    author = models.ForeignKey(User)
    category = models.CharField(max_length=1,
        choices=CATEGORIES)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    
    objects = models.Manager()
    cat = CategoryManager()

    class Meta:
        ordering = ['-date_modified']

    def get_absolute_url(self):
        return reverse('issue_detail', kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.title

class IssueModeration(models.Model):
    PRIORITY = (
        ('C', 'Critical'),
        ('H', 'High'),
        ('M', 'Med'),
        ('L', 'Low'),
    )
    STATUS = (
        ('O', 'Open'),
        ('R', 'Closed: Resolved'),
        ('M', 'Closed: Merged'),
        ('W', 'Closed: Wont Fix'),
        ('S', 'Closed: Spam'),
    )
    issue = models.OneToOneField(Issue)
    priority = models.CharField(max_length=1,
        choices=PRIORITY,
        blank=True)
    status = models.CharField(max_length=1,
        choices=STATUS,
        default='O',
        blank=True)
    assigned_to = models.ForeignKey(User, blank=True, null=True)

    def __unicode__(self):
        return self.issue.title

class IssueComment(models.Model):
    issue = models.ForeignKey(Issue)
    content = models.TextField()
    author = models.ForeignKey(User)

    def get_absolute_url(self):
        return reverse('issue_detail', kwargs={'pk': self.issue.pk})

    def __unicode__(self):
        return "{1}'s comment on {0}".format(self.issue,self.author)

class IssueNotification(models.Model):
    message = models.TextField()
    notification_for_user = models.ForeignKey(User)
    viewed = models.BooleanField(default=False)

    def __unicode__(self):
        return "{0}: {1}".format(self.notification_for_user,self.message)

issuetracker_proj/issuetracker/forms.py
from django import forms
from .models import Issue, IssueModeration, IssueComment

class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ('title','description', 'category',)

class IssueModerationForm(forms.ModelForm):
    class Meta:
        model = IssueModeration
        fields = ('priority','status','assigned_to')

class IssueCommentCreateForm(forms.ModelForm):
    class Meta:
        model = IssueComment
        fields = ('content',)

issuetracker_proj/issuetracker/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from .models import Issue, IssueModeration, IssueComment
from .forms import IssueForm, IssueModerationForm, IssueCommentCreateForm
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, \
    UpdateView, TemplateView

class IssueListView(ListView):
    """ Displays list of all issues
    on app home page, along with
    new issue submit form. """

    model = Issue
    template_name = 'issuetracker/index.html'
    context_object_name = 'issues'
    paginate_by = 5
    success_url = '/issue/'

    def get_context_data(self,*args,**kwargs):
        context = super(IssueListView, self).get_context_data(**kwargs)
        context['issueform'] = IssueForm()
        return context

class IssueDetailView(DetailView):
    """ Displays issue details along
    with comments and moderation tools."""

    model = Issue
    template_name = 'issuetracker/detail.html'
    context_object_names = 'issue'

    def get_context_data(self,*args,**kwargs):
        context = super(IssueDetailView, self).get_context_data(**kwargs)
        context['commentform'] = IssueCommentCreateForm()
        return context

class IssueCreateView(CreateView):
    """View for new issue form, notice
    that a template has been provided even 
    though the form appears in IssueListView.
    Any errors in the form will redirect to this
    template."""

    form_class = IssueForm
    template_name= 'issuetracker/new_issue.html'

    def form_valid(self,form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        self.object = obj
        return HttpResponseRedirect(self.get_success_url())

class IssueUpdateView(UpdateView):
    """Updates existing issue. Permissions
    (i.e only author can update issue) are handled
    on the template side. Not sure if its a good thing."""

    model = Issue
    fields = ['title','description','category']
    template_name = 'issuetracker/edit_issue.html'

class IssueCommentCreateView(CreateView):
    model = IssueComment
    template_name = 'issuetracker/new_comment.html'
    fields = ['content']

    def form_valid(self, form):
        parent_issue = Issue.objects.get(pk=self.kwargs['pk'])
        form.instance.author = self.request.user
        form.instance.issue = parent_issue
        return super(IssueCommentCreateView, self).form_valid(form)

class IssueModerationView(UpdateView):
    """Displays moderation fields, which were
    automatically set to default values upon
    creation of the issue instance via signals"""

    slug_field = 'issue_id'
    slug_url_kwarg = 'issue_id'
    model = IssueModeration
    template_name = 'issuetracker/moderate.html'
    fields = ['priority','status','assigned_to']

    def get_success_url(self):
        return reverse('issue_detail', kwargs={'pk': self.kwargs['issue_id']})



class IssueNotificationsView(TemplateView):
    """Displays all read and unread notifications
    for a user and changes the viewed field to true"""

    template_name='issuetracker/notifications.html'

    def get_context_data(self, **kwargs):
        """ Not sure if this is the right way to
        add context. Could be better. """
        user = self.request.user
        user_unread = user.issuenotification_set.filter(viewed=False)
        user_read = user.issuenotification_set.filter(viewed=True)
        context = super(IssueNotificationsView, self).get_context_data(**kwargs)
        context.update({'user_unread': user_unread, 'user_read': list(user_read)})
        for msg in user_unread:
            msg.viewed = True
            msg.save()
        return context

issuetracker_proj/issuetracker/templates/issuetracker/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} MN Issue: {{ issue.title }} {% endblock %}

{%block content %}
<h2> {{ issue.title }} </h2>
<div class="col-md-4 well">
<p> Description: {{ issue.description }} </p>
<p> Category: {{ issue.get_category_display }} </p>
<p> Author:  {{ issue.author }} </p>

{% if user == issue.author %}
    <p><a href="{% url 'issue_update' issue.pk%}">Edit</a></p>
{% else %}

{% endif %}

<h2> Timeline Here.. </h2>
</div>

<div class="col-md-8 ">
<form action="{% url 'issue_comment_create' issue.pk %}" method="post"> 
    {% csrf_token %}
    {{ commentform.as_p }}
    <button type="submit" name="submit" class="btn btn-primary"> Add Comment </button>
</form>
<hr/>
{%for comment in issue.issuecomment_set.all %}
<p>{{comment.content}} - {{comment.author}}</p>
{% endfor %}
</div>

{% endblock%}

issuetracker_proj/issuetracker/templates/issuetracker/edit_issue.html
{% if user == issue.author %}
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>
{% else %}
    <p> You are not authrorized to view this part. </p>
{% endif %}

issuetracker_proj/issuetracker/templates/issuetracker/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load humanize %}

{%block title %}
Issue Tracker Home
{% endblock %}

{% block content %}
<!-- Script for ToDo list -->
<script> 
$(document).ready(function () {
    var todoList = document.getElementById('todoList');
    $('#saveAll').click(funciton (e) {
        e.preventDefault();
        localStorage.setItem('todoList',todoList.innerHTML);
    });
});

</script>


<!-- --------------Issue Tracker Code Here------------- -->
<h2> Issue Tracker </h2>
<!-- Modal Dialog for adding new issue form-->
<button class="btn btn-success btn-md" data-toggle="modal" data-target="#myModal">
  <span class="glyphicon glyphicon-plus"></span> New Ticket
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new Ticket</h4>
      </div>
      <div class="modal-body">
        <form action="/issue/new/" method="post">
        {% csrf_token %}
        {{ issueform.as_p }}
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" name="submit" class="btn btn-primary"> Add! </button>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- End modal-->

<!-- List of all issues -->
<table class="table table-hover issue-table">
<tr>
<th class="col-lg-6 col-md-6 col-sm-6 col-xs-6">Issue </th>
<th> Last updated </th>
<th> Category </th>
<th> Status </th>
{% if perms.issuetracker.can_modify_itmod %}
<th> Priority </th>
<th> Set </th>
{% endif %}

</tr>
{% for issue in issues %}
<tr>
<td> 
    <a href="{% url 'issue_detail' issue.pk %}"> {{ issue }} </a>
</td>
<td>{{ issue.date_modified|naturaltime }}</td>
<td><span class="label label-default"> {{ issue.get_category_display }}</span></td>
<td> {{ issue.issuemoderation.get_status_display }}</td>
{% if perms.issuetracker.can_modify_itmod %}
<td> {% if issue.priority %}
       {{ issue.get_priority_display }}
     {% else %}
       N/A
     {% endif %}
</td>
<td> 
        <!-- Button trigger modal -->
        <button class="btn btn-default btn-xs" data-toggle="modal" data-target="#setModal{{ issue.pk }}">
          <span class="glyphicon glyphicon-wrench"></span> 
        </button>
        <!-- Modal -->
        <div class="modal fade" id="setModal{{ issue.pk }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
              </div>
              <div class="modal-body">
                ...
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
              </div>
            </div>
          </div>
        </div>
</td>
{% endif %}
</tr>
{% endfor %}
</table>
<!-- End list of issues -->

<!-- Pagination
Graciously copied from: https://gist.github.com/BenAtWide/6506926
 -->
{% if is_paginated %}
<div class="text-center" >
<ul class="pagination">
{% if page_obj.has_previous %}
<li><a href="?page={{ page_obj.previous_page_number }}">
{% else %}
<li class="disabled"><a href="#">
{% endif %}
&laquo;</a></li>
{% for p in page_obj.paginator.page_range %}
<li class="{% if p == page_obj.number %}active{% endif %}"><a href="?page={{ p }}">{{ p }}</a></li>
{% endfor %}
{% if page_obj.has_next %}
<li><a href="?page={{ page_obj.next_page_number }}">
{% else %}
<li class="disabled"><a href="#">
{% endif %}
&raquo;</a></li>
</ul>
</div>
{% endif %}

{% endblock %}

issuetracker_proj/issuetracker/templates/issuetracker/moderate.html
{% if perms.issuetracker.can_modify_itmod %}
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>
{% else %}
    <p> You're not supposed to be here ;) </p>
{% endif %}

issuetracker_proj/issuetracker/templates/issuetracker/modform.html
<form action="" method="post">
        {% csrf_token %}
        {{ mod_form.as_p }}
        <button type="submit" name="submit" class="btn btn-primary"> Add! </button>
      </div>

issuetracker_proj/issuetracker/templates/issuetracker/new_comment.html
<form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
</form>

issuetracker_proj/issuetracker/templates/issuetracker/new_issue.html
<form action="/issue/new/" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="submit" class="btn btn-primary"> Add! </button>
        </form>

issuetracker_proj/issuetracker/templates/issuetracker/notifications.html
Unread: 
<ul>
{% for msg in user_unread %}
    <li> {{ msg }} </li>
{% endfor %}
</ul>

Already read: 

<ul>
{% for msg in user_read %}
    <li> {{ msg }} </li>
{% endfor %}
</ul>

issuetracker_proj/templates/base.html
{% load mytags %}
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'style.css' %}" rel="stylesheet" media="screen">
    <link rel="stylesheet" href="{% static 'font-awesome-4.0.3/css/font-awesome.min.css' %}" rel="stylesheet">
    <title>Nagari: {%block title%} {% endblock %}</title>
</head>
<body>
    <div class="container">
    
    <!-- Navbar -->
        <nav class="navbar navbar-default" role="navigation">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">MN Issue Tracker</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><a href="#">Stats</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Filters <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">By staff member</a></li>
                    <li><a href="#">By priority</a></li>
                    <li><a href="#">By Category</a></li>
                  </ul>
                </li>
              </ul>
              <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
              </form>
              <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                
                <li><a href="{% url 'issue_notifications_list' %}"> <span class="badge alert-danger" style="background-color:#e74c3c; color:white;">{% unread user %}</span> new</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Hi, {{ user.username }} <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Profile</a></li>
                    <li><a href="#">Inbox</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'issue_logout' %}">Logout</a></li>
                  </ul>
                  </li>
                {% else %}
                <li><a href="#">Sign up</a></li>
                <li><a href="{% url 'issue_login' %}"> Login </a></li>
                {% endif %}
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
    <!-- End Navbar -->

            {% block content %}
            {% endblock %}
    </div><!-- Container -->

<!-- Javascript -->
        <script src="{% static 'bootstrap/js/jquery.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

issuetracker_proj/templates/login.html
{% if form.errors %}
    <p class="text-warning">
    Username/password didn't match.
    </p>
{% endif %}

<form role="form" class="form-horizontal" method="post" action="{% url 'issue_login' %}">
{% csrf_token %}
{{ form }}
<input class="btn btn-success" type="submit" value="Login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>